### ISSUE TITLE
Translation for different languages

### ISSUE THREAD

**Issue by gsterling** [Shuggaloaf/Simple_NPC_Generator#1]
Would you be open to have everything translatable? I'd try to supply a german translation and even more german sounding names.

I'd like to use the generator, but don't want to translate everything on the fly while playing or creating.

**Comment by Shuggaloaf** [comment]
Sure, I'd be open to that! 

Admittedly I have no idea how to implement multiple languages into a module (this is my 1st). If you have knowledge on that I'm be happy to hear it, otherwise I'd have to do some investigating. (I would guess it's probably not too hard though)

**Comment by gsterling** [comment]
Sorry, I don't habe any expertise with modules for foundry myself.

**Comment by ChuckMoe** [comment]
The way [Foundry handles it](https://foundryvtt.com/article/localization/) seems to be with a json file for a language. As the translation files are merged with every startup of the server, you would no longer be able to just remove the module after importing the macro.

If you wanna do it the hacky way, you can also transform the data structure to something like this
```javascript
var demeanor = {
  "en": [localized list]
  "de": [localized list]
};
console.log(demeanor[game.system.languages.first().lang][new Roll("1d100")]);
```

**Comment by Shuggaloaf** [comment]
Thanks Chuck. I appreciate the code you supplied. I'm guessing you already see the negative of doing it that way since it would almost double the code for every language. I had actually looked into it and came to the same conclusion as you. Since without resorting to hacky means would mean not being able to remove the module, I just kind of have this on hold right now. 

On the one hand it's probably fine. Most people probably leave the module active anyway, but I just hate to take away that option. On the other hand, there are some other features I'd like to perhaps one day add (like having a button on the generated chat message that allows a user to save the info to a journal entry) that would pretty much require me making this a full-fledged module anyway. 

This "limbo" status is the only reason I haven't closed/resolved the Issue yet. But I think I will go ahead and mark this Closed as Not Planned for now. 

Thanks again!

**Comment by Shuggaloaf** [comment]
Closing for now as not planned. Adding this would require making changes to the module that I'm not sure I want to make at this time. 

However, if/when I do, then adding localization will be one of my 1st updates.
