### ISSUE TITLE
Compatibility with V10

### ISSUE THREAD

**Issue by davelamorte** [Shuggaloaf/Simple_NPC_Generator#3]
Can you please add compatibility with V10? I use this module so much! Thank you.

**Comment by Shuggaloaf** [comment]
Hi davelmorte! Glad to hear you get a lot of use out of the module. 

This generator is something I use at my table a lot so I thought I'd share it with others. I'm still using FVTT version 9 myself and I typically do not update to a new core version until most of the mods I use are available. As of now, 2/3 of my mods are not compatible with version 10. So I *probably* will not be updating the NPC Generator until I personally move to v10. 

*BUT* I am quite interested to see the new V10 features. This weekend I will likely be installing v10 on a VM so I can check it out. I'll take a look at how difficult the programing changes are and, if they aren't bad, then I will go ahead and put out an update. Otherwise it will probably be several weeks at least.

**Comment by davelamorte** [comment]
Thank you for taking the time for this!
Yes V10 isn't working on my world as well... too many broken things. But your module is definitely one that I wouldn't want to miss! Super useful!

**Comment by AurelTristen** [comment]
Just wanted to throw in my support for a V10 update and my thanks for the module. I use this to help me during prep, but have also relied on All Goblins Have Names (It randomly pulls from a name list when you drag out an NPC. Super useful on the fly, but no V10 support in sight).
My players are the type to ask everyone their name, so modules like these are really helpful. Thanks for making it and supporting it!

**Comment by Shuggaloaf** [comment]
@davelamorte @AurelTristen 

Sorry for the delay! I have incorporated eturino's pull request which should make this compatible with v10. As I am still on v9, would one of you mind checking the new release and making sure it is compatible?

**Comment by davelamorte** [comment]
Success!!!
It seems to be working great on my V10!
Thank you so much for this!

**Comment by Shuggaloaf** [comment]
Great! Glad to hear it's working as expected. I'm surprised all it took was such a small change. 

And the thanks all goes to @eturino for this one. :)
